In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
transactions = pd.read_csv(
    "../data/raw/transactions_train.csv",
    parse_dates=["t_dat"],
    dtype={
        "article_id": str,
        "customer_id": str,
        "price": float,
        "sales_channel_id": int,
    },
)
transactions.shape

(31788324, 5)

In [3]:
transactions.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,0505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,0685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,0685687004,0.016932,2

In [ ]:
transactions = transactions[transactions["t_dat"] >= "2020-03-01"].copy()
transactions.shape

(8901919, 5)

In [9]:
np.random.seed(42)
sampled_users = (
    transactions["customer_id"]
    .drop_duplicates()
    .sample(50000, random_state=42)
)

df = transactions[transactions["customer_id"].isin(sampled_users)].copy()
df.shape

(569917, 5)

In [10]:
df.to_parquet("../data/processed/transactions_sample.parquet", index=False)

In [11]:
articles = pd.read_csv(
    "../data/raw/articles.csv",
    dtype={"article_id": str},
)

customers = pd.read_csv(
    "../data/raw/customers.csv",
    dtype={"customer_id": str},
)

articles.to_parquet("../data/processed/articles.parquet", index=False)
customers.to_parquet("../data/processed/customers.parquet", index=False)

In [12]:
articles.shape, customers.shape

((105542, 25), (1371980, 7))

In [13]:
df.dtypes

t_dat               datetime64[ns]
customer_id                 object
article_id                  object
price                      float64
sales_channel_id             int32
dtype: object

In [14]:
df.isnull().sum()

t_dat               0
customer_id         0
article_id          0
price               0
sales_channel_id    0
dtype: int64

In [15]:
df.describe()

                               t_dat          price  sales_channel_id
count                         569917  569917.000000     569917.000000
mean   2020-06-12 11:57:11.040660224       0.027009          1.739206
min              2020-03-01 00:00:00       0.000322          1.000000
25%              2020-04-26 00:00:00       0.016932          1.000000
50%              2020-06-17 00:00:00       0.025407          2.000000
75%              2020-07-28 00:00:00       0.033881          2.000000
max              2020-09-22 00:00:00       0.506780          2.000000
std                              NaN       0.017132          0.439068